<?php
require_once "class/system/includes.php";
require_once "class/Candidat.php";
// tester si l'utilisateur accepte d'utiliser ORCID
if(!empty($_GET["code"])){
    $code = $_GET["code"];

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://orcid.org/oauth/token");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "client_id=APP-WINEWRK2EVHK9GD9&client_secret=78c62802-32c9-42a6-8133-e8b967443472&grant_type=authorization_code&redirect_uri=http://oneway-it.com/projets/concours/register.php&code=$code");
    curl_setopt($ch, CURLOPT_POST, 1);

    $headers = array();
    $headers[] = "Accept: application/json";
    $headers[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);

    $data=json_decode($result);

    if(isset($data->error)){
        die($data->error_description);
    }

    // Teset si le candidat existe déjà
    $candidat = Candidat::checkOrcid($data->orcid);
    //$candidat = Candidat::checkOrcid("0000-0002-2268-2626");
    if($candidat===false){
        $candidat = new Candidat();
        $candidat->name=$data->name;
        $candidat->orcid=$data->orcid;
        $candidat->register();
    }
    $_SESSION["user"]=[];
    $_SESSION["user"]["id"]=$candidat->id;
    $_SESSION["user"]["name"]=$candidat->name;
    $_SESSION["user"]["orcid"]=$candidat->orcid;

    redirect("profil.php");



}
elseif(!empty($_GET["error"]) and $_GET["error"]=="access_denied"){
    die("User denied access");
}
?>
